"use client";
import {useEffect,useMemo,useState} from "react";import {useAdminAuth} from "../../lib/useAdminAuth";import {supabase} from "../../lib/supabase";import {tenant} from "../../lib/tenant";
const labels={recibido:"Recibido",confirmado:"Confirmado",preparando:"Preparando",listo:"Listo",en_camino:"En camino",entregado:"Entregado",cancelado:"Cancelado"};
export default function Admin(){const {loading,user}=useAdminAuth(),[orders,setOrders]=useState([]),[q,setQ]=useState(""),[filter,setFilter]=useState("todos"),[busy,setBusy]=useState("");
async function load(){const {data}=await supabase.from("colo_orders").select("*").order("created_at",{ascending:false}).limit(200);setOrders(data||[])}
useEffect(()=>{if(user)load()},[user]);
const list=useMemo(()=>orders.filter(o=>(filter==="todos"||o.status===filter)&&(!q||[o.reference,o.full_name,o.phone,o.municipality,o.locality].join(" ").toLowerCase().includes(q.toLowerCase()))),[orders,q,filter]);
async function status(id,value){setBusy(id);await supabase.from("colo_orders").update({status:value,updated_at:new Date().toISOString()}).eq("id",id);await load();setBusy("")}
async function logout(){await supabase.auth.signOut();location.href="/admin/login"}
if(loading||!user)return <main className="adminShell"><p>Cargando panel…</p></main>;
const today=orders.filter(o=>new Date(o.created_at).toDateString()===new Date().toDateString()),pending=orders.filter(o=>!["entregado","cancelado"].includes(o.status)),sales=today.filter(o=>o.status!=="cancelado").reduce((a,o)=>a+Number(o.total),0);
return <main className="adminShell"><header className="adminTop"><div className="adminBrand"><img src={tenant.logo} alt={tenant.name}/><div><small>Centro de control</small><b>{tenant.name}</b></div></div><button onClick={logout}>Salir</button></header><section className="adminWelcome"><div><p>Operación de hoy</p><h1>Pedidos</h1></div><span>{new Date().toLocaleDateString("es-CU",{day:"numeric",month:"short"})}</span></section><section className="adminMetrics"><article><span>Hoy</span><b>{today.length}</b><small>pedidos</small></article><article><span>Pendientes</span><b>{pending.length}</b><small>por completar</small></article><article><span>Ventas hoy</span><b>{sales.toLocaleString("es-CU")}</b><small>{tenant.currency}</small></article></section><section className="adminTools"><input placeholder="Buscar pedido, cliente o teléfono" value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos los estados</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></section><section className="adminOrders">{list.length?list.map(o=><article className="adminOrder" key={o.id}><div className="adminOrderHead"><div><b>#{o.reference}</b><span>{new Date(o.created_at).toLocaleString("es-CU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</span></div><strong>{Number(o.total).toLocaleString("es-CU")} {o.currency}</strong></div><div className="adminCustomer"><b>{o.full_name}</b><a href={"tel:"+o.phone}>{o.phone}</a><span>{o.mode==="pickup"?"Recogida en tienda":[o.locality,o.municipality].filter(Boolean).join(", ")}</span></div><div className="adminItems">{(o.items||[]).map((x,i)=><span key={i}>{x.quantity}× {x.name}</span>)}</div><label className="adminStatus">Estado<select disabled={busy===o.id} value={o.status} onChange={e=>status(o.id,e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></article>):<p>No hay pedidos con ese filtro.</p>}</section></main>}