// Productos con precios CUP registrados desde fotos de tienda.
export const products=[
  {
    "id": 1001,
    "sharedProductId": "almendras-chocolate",
    "n": "Almendras con chocolate con leche",
    "d": "Member’s Mark · Frasco 1,36 kg",
    "c": "Frutos secos",
    "p": 25500,
    "currency": "CUP",
    "img": "/products/real/almendras-chocolate.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164901.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164901.jpg",
    "stock": null
  },
  {
    "id": 1002,
    "sharedProductId": "pasas-chocolate",
    "n": "Pasas cubiertas de chocolate",
    "d": "Member’s Mark · Frasco 1,53 kg",
    "c": "Frutos secos",
    "p": 24500,
    "currency": "CUP",
    "img": "/products/real/pasas-chocolate.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164902_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164902_1.jpg",
    "stock": null
  },
  {
    "id": 1003,
    "sharedProductId": "pobeda-madagascar",
    "n": "Chocolate Pobeda Madagascar",
    "d": "Chocolate negro · 55 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3300,
    "currency": "CUP",
    "img": "/products/real/pobeda-madagascar.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164905_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164905_1.jpg",
    "stock": null
  },
  {
    "id": 1004,
    "sharedProductId": "pobeda-ecuador",
    "n": "Chocolate Pobeda Ecuador",
    "d": "Chocolate con leche · 45 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3500,
    "currency": "CUP",
    "img": "/products/real/pobeda-ecuador.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164905_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164905_1.jpg",
    "stock": null
  },
  {
    "id": 1005,
    "sharedProductId": "pobeda-cote-ivoire",
    "n": "Chocolate Pobeda Côte d’Ivoire",
    "d": "Chocolate negro · 60 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3700,
    "currency": "CUP",
    "img": "/products/real/pobeda-cote-ivoire.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164905_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164905_1.jpg",
    "stock": null
  },
  {
    "id": 1006,
    "sharedProductId": "lacasa-menta",
    "n": "Chocolate negro con menta Lacasa",
    "d": "70 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3900,
    "currency": "CUP",
    "img": "/products/real/lacasa-menta.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164907_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164907_1.jpg",
    "stock": null
  },
  {
    "id": 1007,
    "sharedProductId": "bentons-fresa",
    "n": "Mini galletas Benton's de fresa",
    "d": "Strawberry Mini Fudge Dipped Cookie Bites · Bolsa",
    "c": "Alimentos",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/bentons-fresa.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164913_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164913_1.jpg",
    "stock": null
  },
  {
    "id": 1008,
    "sharedProductId": "bentons-arandano",
    "n": "Mini galletas Benton's de arándano y limón",
    "d": "Blueberry Lemon Mini Fudge Dipped Cookie Bites · Bolsa",
    "c": "Alimentos",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/bentons-arandano.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164913_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164913_1.jpg",
    "stock": null
  },
  {
    "id": 1009,
    "sharedProductId": "choceur-cups",
    "n": "Chocolate Choceur con mantequilla de maní",
    "d": "Milk Chocolate Peanut Butter Cups · Bolsa",
    "c": "Alimentos",
    "p": 5600,
    "currency": "CUP",
    "img": "/products/real/choceur-cups.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164915_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164915_1.jpg",
    "stock": null
  },
  {
    "id": 1010,
    "sharedProductId": "mounds",
    "n": "Chocolates Mounds de coco",
    "d": "Paquete de 4 barras snacksize",
    "c": "Alimentos",
    "p": 2500,
    "currency": "CUP",
    "img": "/products/real/mounds.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164918_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164918_1.jpg",
    "stock": null
  },
  {
    "id": 1011,
    "sharedProductId": "milky-way",
    "n": "Chocolate Milky Way",
    "d": "Chocolate con leche, caramelo y nougat · 48 g",
    "c": "Alimentos",
    "p": 2500,
    "currency": "CUP",
    "img": "/products/real/milky-way.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164921.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164921.jpg",
    "stock": null
  },
  {
    "id": 1012,
    "sharedProductId": "papel-excelencia",
    "n": "Papel higiénico La Excelencia",
    "d": "Super Suave · 4 rollos · 2 capas",
    "c": "Aseo",
    "p": 1250,
    "currency": "CUP",
    "img": "/products/real/papel-excelencia.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164927_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164927_1.jpg",
    "stock": null
  },
  {
    "id": 1013,
    "sharedProductId": "members-pacs",
    "n": "Cápsulas de detergente Member's Mark",
    "d": "Laundry Power Pacs · Blooming Breeze · 65 unidades",
    "c": "Aseo",
    "p": 21000,
    "currency": "CUP",
    "img": "/products/real/members-pacs.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164933.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164933.jpg",
    "stock": null
  },
  {
    "id": 1014,
    "sharedProductId": "tide-spring",
    "n": "Cápsulas de detergente Tide Spring Meadow",
    "d": "Pods · Bolsa",
    "c": "Aseo",
    "p": 19000,
    "currency": "CUP",
    "img": "/products/real/tide-spring.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164936_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164936_1.jpg",
    "stock": null
  },
  {
    "id": 1015,
    "sharedProductId": "gain-original-grande",
    "n": "Cápsulas de detergente Gain Original",
    "d": "Bolsa grande · Vista del envase disponible",
    "c": "Aseo",
    "p": 18700,
    "currency": "CUP",
    "img": "/products/real/gain-original-grande.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164936_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164936_1.jpg",
    "stock": null
  },
  {
    "id": 1016,
    "sharedProductId": "tide-oxi",
    "n": "Cápsulas Tide Ultra Oxi",
    "d": "Power Pods · Bolsa 757 g",
    "c": "Aseo",
    "p": 9000,
    "currency": "CUP",
    "img": "/products/real/tide-oxi.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164939.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164939.jpg",
    "stock": null
  },
  {
    "id": 1017,
    "sharedProductId": "gain-suavizante",
    "n": "Suavizante Gain Original",
    "d": "Fabric Softener · 306 mL",
    "c": "Aseo",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/gain-suavizante.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164949_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164949_1.jpg",
    "stock": null
  },
  {
    "id": 1018,
    "sharedProductId": "magali-mora",
    "n": "Gel de baño Magali Mora",
    "d": "Blackberry · Botella",
    "c": "Aseo",
    "p": 2300,
    "currency": "CUP",
    "img": "/products/real/magali-mora.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164957_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164957_1.jpg",
    "stock": null
  },
  {
    "id": 1019,
    "sharedProductId": "snonas-candy",
    "n": "Gel de baño S'nonas Candy Shop",
    "d": "Botella",
    "c": "Aseo",
    "p": 3300,
    "currency": "CUP",
    "img": "/products/real/snonas-candy.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164957_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164957_1.jpg",
    "stock": null
  },
  {
    "id": 1020,
    "sharedProductId": "snonas-honey",
    "n": "Colonia S'nonas Fraîche amarilla",
    "d": "Botella 750 mL",
    "c": "Aseo",
    "p": 3300,
    "currency": "CUP",
    "img": "/products/real/snonas-honey.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164957_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164957_1.jpg",
    "stock": null
  },
  {
    "id": 1021,
    "sharedProductId": "dicora-avena",
    "n": "Gel de baño Dicora Yogurt y Avena",
    "d": "Urban Fit · Shower Cream · 400 mL",
    "c": "Aseo",
    "p": 4200,
    "currency": "CUP",
    "img": "/products/real/dicora-avena.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1022,
    "sharedProductId": "dicora-citrus",
    "n": "Gel de baño Dicora Citrus y Peach",
    "d": "Urban Fit · 400 mL",
    "c": "Aseo",
    "p": 4200,
    "currency": "CUP",
    "img": "/products/real/dicora-citrus.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1023,
    "sharedProductId": "snonas-body",
    "n": "Crema corporal S'nonas PH",
    "d": "Body Milk Hidratante · 1.000 mL",
    "c": "Aseo",
    "p": 3350,
    "currency": "CUP",
    "img": "/products/real/snonas-body.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1024,
    "sharedProductId": "snonas-coco-pina",
    "n": "Gel de baño S'nonas Coco y Piña",
    "d": "Botella 750 mL",
    "c": "Aseo",
    "p": 3850,
    "currency": "CUP",
    "img": "/products/real/snonas-coco-pina.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1025,
    "sharedProductId": "peine-flexys",
    "n": "Peine antipiojos Flexys",
    "d": "Peine de doble cara · 1 unidad",
    "c": "Aseo",
    "p": 1000,
    "currency": "CUP",
    "img": "/products/real/peine-flexys.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165013_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165013_1.jpg",
    "stock": null
  },
  {
    "id": 1026,
    "sharedProductId": "balsamos-paul-frank",
    "n": "Bálsamos labiales Paul Frank",
    "d": "Set de 6 piezas",
    "c": "Aseo",
    "p": 2000,
    "currency": "CUP",
    "img": "/products/real/balsamos-paul-frank.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165016_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165016_1.jpg",
    "stock": null
  },
  {
    "id": 1027,
    "sharedProductId": "ventilador-pure-silk",
    "n": "Mini ventilador Pure Silk",
    "d": "Portátil · Funciona con pilas",
    "c": "Accesorios",
    "p": 4800,
    "currency": "CUP",
    "img": "/products/real/ventilador-pure-silk.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165019_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165019_1.jpg",
    "stock": null
  },
  {
    "id": 1028,
    "sharedProductId": "nordic-ar",
    "n": "Perlas aromáticas Nordic Air",
    "d": "In-wash Fragrance Booster · 297 g",
    "c": "Aseo",
    "p": 4500,
    "currency": "CUP",
    "img": "/products/real/nordic-ar.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1029,
    "sharedProductId": "un-n09",
    "n": "Perlas aromáticas Un N.09",
    "d": "Laundry Scent Booster · Fine Pine",
    "c": "Aseo",
    "p": 7500,
    "currency": "CUP",
    "img": "/products/real/un-n09.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1030,
    "sharedProductId": "ohmy-azul",
    "n": "Champú Oh My azul",
    "d": "Antiqueda · 300 mL",
    "c": "Aseo",
    "p": 3450,
    "currency": "CUP",
    "img": "/products/real/ohmy-azul.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1031,
    "sharedProductId": "ohmy-rojo",
    "n": "Champú Oh My rojo",
    "d": "Desmaia · 300 mL",
    "c": "Aseo",
    "p": 3450,
    "currency": "CUP",
    "img": "/products/real/ohmy-rojo.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1032,
    "sharedProductId": "febreze-luxe",
    "n": "Ambientador Febreze Luxe",
    "d": "Air · Summer Golden Hour",
    "c": "Aseo",
    "p": 6000,
    "currency": "CUP",
    "img": "/products/real/febreze-luxe.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "salud-salfuman",
    "n": "Aguafuerte La Salud Salfumán",
    "d": "Botella negra · Cierre blanco",
    "c": "Aseo",
    "p": 2900,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165036.jpg",
    "id": 2001,
    "img": "/products/real/salud-salfuman.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165036.jpg",
    "stock": null
  },
  {
    "sharedProductId": "salud-multiusos",
    "n": "Multiusos y limpiacristales La Salud",
    "d": "2 en 1 · Botella de líquido azul",
    "c": "Aseo",
    "p": 2900,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165039_1.jpg",
    "id": 2002,
    "img": "/products/real/salud-multiusos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165039_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "salud-antical-spray",
    "n": "Antical La Salud Brillo Total",
    "d": "2 en 1 · Baños y duchas · Pulverizador",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165039_1.jpg",
    "id": 2003,
    "img": "/products/real/salud-antical-spray.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165039_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "khawla-lavavajillas",
    "n": "Lavavajillas Khawla",
    "d": "Botella blanca · Tapón verde",
    "c": "Aseo",
    "p": 1200,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165045.jpg",
    "id": 2004,
    "img": "/products/real/khawla-lavavajillas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165045.jpg",
    "stock": null
  },
  {
    "sharedProductId": "dawn-crisp-lilac",
    "n": "Lavavajillas Dawn Powerwash Crisp Lilac",
    "d": "Recarga · 16 oz",
    "c": "Aseo",
    "p": 21500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165050_1.jpg",
    "id": 2005,
    "img": "/products/real/dawn-crisp-lilac.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165050_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "lex-wc-limp",
    "n": "Limpiador Lex Clean WC Limp",
    "d": "Desincrustante · 1 litro",
    "c": "Aseo",
    "p": 4900,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165055_1.jpg",
    "id": 2006,
    "img": "/products/real/lex-wc-limp.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165055_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "pano-blanco",
    "n": "Paño de limpieza blanco",
    "d": "Unidad · Medidas por confirmar",
    "c": "Aseo",
    "p": 700,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165059_1.jpg",
    "id": 2007,
    "img": "/products/real/pano-blanco.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165059_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "pano-amarillo",
    "n": "Paño de limpieza amarillo",
    "d": "Unidad · Medidas por confirmar",
    "c": "Aseo",
    "p": 1150,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165059_1.jpg",
    "id": 2008,
    "img": "/products/real/pano-amarillo.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165059_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "nature-cinnamon",
    "n": "Enjuague bucal Nature Fresh Cinnamon",
    "d": "532 mL",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165106_1.jpg",
    "id": 2009,
    "img": "/products/real/nature-cinnamon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165106_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "nature-spearmint",
    "n": "Enjuague bucal Nature Fresh Spearmint",
    "d": "710 mL",
    "c": "Aseo",
    "p": 4500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165106_1.jpg",
    "id": 2010,
    "img": "/products/real/nature-spearmint.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165106_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "mister-pack-congelacion",
    "n": "Bolsas para congelación Mister Pack",
    "d": "15 bolsas · 28 × 42 cm · 6 L",
    "c": "Accesorios",
    "p": 1000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165110_1.jpg",
    "id": 2011,
    "img": "/products/real/mister-pack-congelacion.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165110_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "mical-film",
    "n": "Film transparente Mical",
    "d": "Rollo de 30 m",
    "c": "Accesorios",
    "p": 2500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165106_1.jpg",
    "id": 2012,
    "img": "/products/real/mical-film.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165106_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "alfa-molinillos",
    "n": "Molinillos de sal y pimienta Alfa",
    "d": "Set de 2 piezas · Verde",
    "c": "Accesorios",
    "p": 4400,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165114.jpg",
    "id": 2013,
    "img": "/products/real/alfa-molinillos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165114.jpg",
    "stock": null
  },
  {
    "sharedProductId": "summers-eve-fresh",
    "n": "Summer’s Eve Fresh Scent",
    "d": "Caja · Presentación visible",
    "c": "Aseo",
    "p": 1350,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165120.jpg",
    "id": 2014,
    "img": "/products/real/summers-eve-fresh.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165120.jpg",
    "stock": null
  },
  {
    "sharedProductId": "vapour-rub",
    "n": "Vapour Rub Green Stick",
    "d": "Frasco · Family Value Pack",
    "c": "Aseo",
    "p": 1100,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165120.jpg",
    "id": 2015,
    "img": "/products/real/vapour-rub.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165120.jpg",
    "stock": null
  },
  {
    "sharedProductId": "bastoncillos-grandes",
    "n": "Bastoncillos de algodón",
    "d": "Envase redondo grande · Cantidad no legible",
    "c": "Aseo",
    "p": 700,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165123_1.jpg",
    "id": 2016,
    "img": "/products/real/bastoncillos-grandes.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165123_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "palillos",
    "n": "Palillos de madera",
    "d": "Envase con tapa decorada · Colores surtidos",
    "c": "Accesorios",
    "p": 700,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165123_1.jpg",
    "id": 2017,
    "img": "/products/real/palillos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165123_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "truearth-spring",
    "n": "Detergente en tiras Net Zero Co by Tru Earth",
    "d": "Spring Breeze · 20 tiras",
    "c": "Aseo",
    "p": 4500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165128.jpg",
    "id": 2018,
    "img": "/products/real/truearth-spring.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165128.jpg",
    "stock": null
  },
  {
    "sharedProductId": "belle-france-antitransfert",
    "n": "Toallitas antitransferencia Belle France",
    "d": "Caja de 25 unidades",
    "c": "Aseo",
    "p": 3000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165128.jpg",
    "id": 2019,
    "img": "/products/real/belle-france-antitransfert.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165128.jpg",
    "stock": null
  },
  {
    "sharedProductId": "harmony-lemon",
    "n": "Jabón Harmony Lemon",
    "d": "Fruit series · Una pastilla en envoltorio",
    "c": "Aseo",
    "p": 450,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165138.jpg",
    "id": 2020,
    "img": "/products/real/harmony-lemon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165138.jpg",
    "stock": null
  },
  {
    "sharedProductId": "parex-s",
    "n": "Bolsas de basura Parex S",
    "d": "20 L · 40 × 50 cm · 20 bolsas",
    "c": "Aseo",
    "p": 1750,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165144.jpg",
    "id": 2021,
    "img": "/products/real/parex-s.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165144.jpg",
    "stock": null
  },
  {
    "sharedProductId": "parex-m",
    "n": "Bolsas de basura Parex M",
    "d": "35 L · 55 × 60 cm · 30 bolsas",
    "c": "Aseo",
    "p": 2500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165144.jpg",
    "id": 2022,
    "img": "/products/real/parex-m.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165144.jpg",
    "stock": null
  },
  {
    "sharedProductId": "happy-baby-soap",
    "n": "Jabón Happy Baby",
    "d": "Cream soap · Manzanilla y sumac · Caja",
    "c": "Aseo",
    "p": 2500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165150.jpg",
    "id": 2023,
    "img": "/products/real/happy-baby-soap.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165150.jpg",
    "stock": null
  },
  {
    "sharedProductId": "amber-sugar-cookie",
    "n": "Desodorante Amber Sugar Cookie",
    "d": "60 g · Envase rosa",
    "c": "Aseo",
    "p": 3500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165157.jpg",
    "id": 2024,
    "img": "/products/real/amber-sugar-cookie.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165157.jpg",
    "stock": null
  },
  {
    "sharedProductId": "rose-honey",
    "n": "Toallitas húmedas Rose Honey y Camomile",
    "d": "Paquete con tapa rígida · Cantidad no legible",
    "c": "Aseo",
    "p": 1100,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165200.jpg",
    "id": 2025,
    "img": "/products/real/rose-honey.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165200.jpg",
    "stock": null
  },
  {
    "sharedProductId": "ronza-lemon",
    "n": "Toallitas húmedas Ronza Lemon",
    "d": "Paquete de 15 unidades",
    "c": "Aseo",
    "p": 500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165200.jpg",
    "id": 2026,
    "img": "/products/real/ronza-lemon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165200.jpg",
    "stock": null
  },
  {
    "sharedProductId": "astera-kids",
    "n": "Pasta dental Astera Kids",
    "d": "Ice cream · Caja",
    "c": "Aseo",
    "p": 1500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165203.jpg",
    "id": 2027,
    "img": "/products/real/astera-kids.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165203.jpg",
    "stock": null
  },
  {
    "sharedProductId": "colgate-advanced",
    "n": "Pasta dental Colgate Advanced White",
    "d": "100 mL · 140 g",
    "c": "Aseo",
    "p": 1300,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165207.jpg",
    "id": 2028,
    "img": "/products/real/colgate-advanced.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165207.jpg",
    "stock": null
  },
  {
    "sharedProductId": "colgate-triple",
    "n": "Pasta dental Colgate Triple Action",
    "d": "100 mL",
    "c": "Aseo",
    "p": 1200,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165207.jpg",
    "id": 2029,
    "img": "/products/real/colgate-triple.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165207.jpg",
    "stock": null
  },
  {
    "id": 3001,
    "sharedProductId": "futuro-pitillos-200",
    "n": "Pitillos biodegradables Futuro",
    "d": "Paquete de 200 unidades",
    "c": "Accesorios",
    "p": 3000,
    "currency": "CUP",
    "img": "/products/real/futuro-pitillos-200.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165214.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165214.jpg",
    "stock": null
  },
  {
    "id": 3002,
    "sharedProductId": "veslee-aerosol",
    "n": "Pintura en aerosol Veslee",
    "d": "Envase con tapa roja",
    "c": "Accesorios",
    "p": 2000,
    "currency": "CUP",
    "img": "/products/real/veslee-aerosol.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165214.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165214.jpg",
    "stock": null
  },
  {
    "id": 3003,
    "sharedProductId": "tfs-utensilios-3",
    "n": "Set de utensilios TFS",
    "d": "Blíster de 3 piezas",
    "c": "Accesorios",
    "p": 1250,
    "currency": "CUP",
    "img": "/products/real/tfs-utensilios-3.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165214.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165214.jpg",
    "stock": null
  },
  {
    "id": 3004,
    "sharedProductId": "durian-cepillos-5",
    "n": "Cepillos dentales Durian",
    "d": "Paquete de 5 unidades",
    "c": "Aseo",
    "p": 2000,
    "currency": "CUP",
    "img": "/products/real/durian-cepillos-5.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165222.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165222.jpg",
    "stock": null
  },
  {
    "id": 3005,
    "sharedProductId": "hilo-dental",
    "n": "Hilo dental Morgem",
    "d": "Blíster individual",
    "c": "Aseo",
    "p": 550,
    "currency": "CUP",
    "img": "/products/real/hilo-dental.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165219.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165219.jpg",
    "stock": null
  },
  {
    "id": 3006,
    "sharedProductId": "magali-avena",
    "n": "Jabón de manos Magali Avena",
    "d": "Envase con dispensador",
    "c": "Aseo",
    "p": 1800,
    "currency": "CUP",
    "img": "/products/real/magali-avena.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165227.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165227.jpg",
    "stock": null
  },
  {
    "id": 3007,
    "sharedProductId": "personal-care-afeitar",
    "n": "Crema de afeitar Personal Care Men",
    "d": "Extra Thick Regular · 283 g",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "img": "/products/real/personal-care-afeitar.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165236.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165236.jpg",
    "stock": null
  },
  {
    "id": 3008,
    "sharedProductId": "xtracare-afeitar",
    "n": "Crema de afeitar XtraCare",
    "d": "Sensitive Skin",
    "c": "Aseo",
    "p": 3000,
    "currency": "CUP",
    "img": "/products/real/xtracare-afeitar.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165236.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165236.jpg",
    "stock": null
  },
  {
    "id": 3009,
    "sharedProductId": "viking-sensitive",
    "n": "Espuma de afeitar Viking",
    "d": "Sensitive · Envase blanco",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "img": "/products/real/viking-sensitive.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165242.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165242.jpg",
    "stock": null
  },
  {
    "id": 3010,
    "sharedProductId": "tango-verde",
    "n": "Espuma de afeitar Tango",
    "d": "Variante de envase verde",
    "c": "Aseo",
    "p": 1200,
    "currency": "CUP",
    "img": "/products/real/tango-verde.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165242.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165242.jpg",
    "stock": null
  },
  {
    "id": 3011,
    "sharedProductId": "febreze-plug",
    "n": "Dispositivo Febreze Plug",
    "d": "Dispositivo en blíster",
    "c": "Aseo",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/febreze-plug.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165247.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165247.jpg",
    "stock": null
  },
  {
    "id": 3012,
    "sharedProductId": "stinky-bowl-citrus",
    "n": "Gel para inodoro Stinky Bowl",
    "d": "Citrus · Dispensador y 12 aplicaciones",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "img": "/products/real/stinky-bowl-citrus.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165247.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165247.jpg",
    "stock": null
  },
  {
    "id": 3013,
    "sharedProductId": "luv-fresh-tropic",
    "n": "Crema de manos LuvFresh Tropic Garden",
    "d": "30 ml · Blíster individual",
    "c": "Aseo",
    "p": 5500,
    "currency": "CUP",
    "img": "/products/real/luv-fresh-tropic.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165247.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165247.jpg",
    "stock": null
  },
  {
    "id": 3014,
    "sharedProductId": "suavitel-hojas",
    "n": "Hojas suavizantes Suavitel",
    "d": "Field Flowers · Caja de 20 hojas",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "img": "/products/real/suavitel-hojas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165257.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165257.jpg",
    "stock": null
  },
  {
    "id": 3015,
    "sharedProductId": "pure-silk-mini",
    "n": "Mini plancha de cabello Pure Silk",
    "d": "Presentación en caja",
    "c": "Accesorios",
    "p": 5700,
    "currency": "CUP",
    "img": "/products/real/pure-silk-mini.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165257.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165257.jpg",
    "stock": null
  },
  {
    "id": 3016,
    "sharedProductId": "nevada-strawberry",
    "n": "Mascarilla facial Nevada Strawberry",
    "d": "Sobre individual",
    "c": "Aseo",
    "p": 1000,
    "currency": "CUP",
    "img": "/products/real/nevada-strawberry.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165303.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165303.jpg",
    "stock": null
  },
  {
    "id": 3017,
    "sharedProductId": "goraw-chili-lime",
    "n": "Semillas Go Raw Chili Lime",
    "d": "Organic Snacking Seeds",
    "c": "Frutos secos",
    "p": 250,
    "currency": "CUP",
    "img": "/products/real/goraw-chili-lime.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165328.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165328.jpg",
    "stock": null
  },
  {
    "id": 3018,
    "sharedProductId": "aldi-gummy-worms",
    "n": "Gomitas ALDI Gummy Sour Worms",
    "d": "Variety · Bolsa",
    "c": "Alimentos",
    "p": 3500,
    "currency": "CUP",
    "img": "/products/real/aldi-gummy-worms.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165333.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165333.jpg",
    "stock": null
  },
  {
    "id": 3019,
    "sharedProductId": "sour-punch-banana",
    "n": "Sour Punch Bites Banana",
    "d": "Bolsa",
    "c": "Alimentos",
    "p": 1350,
    "currency": "CUP",
    "img": "/products/real/sour-punch-banana.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165333.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165333.jpg",
    "stock": null
  },
  {
    "id": 3020,
    "sharedProductId": "actii-butter-lovers",
    "n": "Palomitas ACT II Butter Lovers",
    "d": "Paquete para microondas",
    "c": "Alimentos",
    "p": 700,
    "currency": "CUP",
    "img": "/products/real/actii-butter-lovers.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165337.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165337.jpg",
    "stock": null
  },
  {
    "id": 3021,
    "sharedProductId": "dove-pudding",
    "n": "Pudín Dove Milk Chocolate",
    "d": "Pudding & Pie Filling · Caja",
    "c": "Alimentos",
    "p": 3500,
    "currency": "CUP",
    "img": "/products/real/dove-pudding.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165341.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165341.jpg",
    "stock": null
  },
  {
    "id": 3022,
    "sharedProductId": "boom-frutos-rojos",
    "n": "Gelatina Boom Frutos Rojos",
    "d": "Caja de 3 sobres · 120 g",
    "c": "Alimentos",
    "p": 1550,
    "currency": "CUP",
    "img": "/products/real/boom-frutos-rojos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165345.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165345.jpg",
    "stock": null
  },
  {
    "id": 3023,
    "sharedProductId": "macrofood-pina",
    "n": "Gelatina Macro Food Piña",
    "d": "Caja de 100 g",
    "c": "Alimentos",
    "p": 1280,
    "currency": "CUP",
    "img": "/products/real/macrofood-pina.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165347.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165347.jpg",
    "stock": null
  },
  {
    "id": 4001,
    "sharedProductId": "oli-pina",
    "n": "Gelatina Oli Piña",
    "d": "Baldom · Caja de 85 g",
    "c": "Alimentos",
    "p": 530,
    "currency": "CUP",
    "img": "/products/real/oli-pina.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165353.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165353.jpg",
    "stock": null
  },
  {
    "id": 4002,
    "sharedProductId": "quaker-granola",
    "n": "Granola Quaker Simply Granola",
    "d": "Oats, Honey, Raisins & Almonds · 1,95 kg",
    "c": "Alimentos",
    "p": 15500,
    "currency": "CUP",
    "img": "/products/real/quaker-granola.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165401.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165401.jpg",
    "stock": null
  },
  {
    "id": 4003,
    "sharedProductId": "kirkland-cashew-clusters",
    "n": "Kirkland Cashew Clusters",
    "d": "Almendras y semillas de calabaza · 907 g",
    "c": "Frutos secos",
    "p": 22000,
    "currency": "CUP",
    "img": "/products/real/kirkland-cashew-clusters.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165401.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165401.jpg",
    "stock": null
  },
  {
    "id": 4004,
    "sharedProductId": "nutrail-cinnamon",
    "n": "Granola NuTrail Cinnamon Pecan",
    "d": "Nut Granola · 624 g",
    "c": "Alimentos",
    "p": 19000,
    "currency": "CUP",
    "img": "/products/real/nutrail-cinnamon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165401.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165401.jpg",
    "stock": null
  },
  {
    "id": 4005,
    "sharedProductId": "purely-cookie-granola",
    "n": "Granola Purely Elizabeth Chocolate Chip",
    "d": "Cookie Granola · Bolsa",
    "c": "Alimentos",
    "p": 15000,
    "currency": "CUP",
    "img": "/products/real/purely-cookie-granola.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165401.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165401.jpg",
    "stock": null
  },
  {
    "id": 4006,
    "sharedProductId": "jif-creamy",
    "n": "Crema de maní Jif Creamy",
    "d": "Frasco de 1,36 kg",
    "c": "Frutos secos",
    "p": 15000,
    "currency": "CUP",
    "img": "/products/real/jif-creamy.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165407.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165407.jpg",
    "stock": null
  },
  {
    "id": 4007,
    "sharedProductId": "kirkland-peanuts",
    "n": "Maní Kirkland Super Extra-Large",
    "d": "Roasted & Salted · Lata de 1,13 kg",
    "c": "Frutos secos",
    "p": 18000,
    "currency": "CUP",
    "img": "/products/real/kirkland-peanuts.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165407.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165407.jpg",
    "stock": null
  },
  {
    "id": 4008,
    "sharedProductId": "southern-cocktail",
    "n": "Maní Southern Grove Cocktail",
    "d": "With Sea Salt · Lata de 454 g",
    "c": "Frutos secos",
    "p": 7000,
    "currency": "CUP",
    "img": "/products/real/southern-cocktail.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165407.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165407.jpg",
    "stock": null
  },
  {
    "id": 4009,
    "sharedProductId": "southern-honey",
    "n": "Maní Southern Grove Honey Roasted",
    "d": "Frasco con tapa amarilla",
    "c": "Frutos secos",
    "p": 6500,
    "currency": "CUP",
    "img": "/products/real/southern-honey.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165407.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165407.jpg",
    "stock": null
  },
  {
    "id": 4010,
    "sharedProductId": "wellsley-peanut-mix",
    "n": "Wellsley Farms Peanut Butter Lovers",
    "d": "Trail Mix · Bolsa de 1,13 kg",
    "c": "Frutos secos",
    "p": 19500,
    "currency": "CUP",
    "img": "/products/real/wellsley-peanut-mix.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165412.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165412.jpg",
    "stock": null
  },
  {
    "id": 4011,
    "sharedProductId": "southern-tropical",
    "n": "Southern Grove Tropical Trail Mix",
    "d": "Bolsa",
    "c": "Frutos secos",
    "p": 10500,
    "currency": "CUP",
    "img": "/products/real/southern-tropical.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165412.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165412.jpg",
    "stock": null
  },
  {
    "id": 4012,
    "sharedProductId": "southern-cajun",
    "n": "Southern Grove Sweet & Spicy Cajun",
    "d": "Trail Mix · Bolsa",
    "c": "Frutos secos",
    "p": 11000,
    "currency": "CUP",
    "img": "/products/real/southern-cajun.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165412.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165412.jpg",
    "stock": null
  },
  {
    "id": 4013,
    "sharedProductId": "southern-indulgent",
    "n": "Southern Grove Indulgent Trail Mix",
    "d": "Bolsa",
    "c": "Frutos secos",
    "p": 10500,
    "currency": "CUP",
    "img": "/products/real/southern-indulgent.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165412.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165412.jpg",
    "stock": null
  },
  {
    "id": 4014,
    "sharedProductId": "gv-cranberry-mix",
    "n": "Great Value Cranberry, Cashew & Almond",
    "d": "Trail Mix · 680 g",
    "c": "Frutos secos",
    "p": 13000,
    "currency": "CUP",
    "img": "/products/real/gv-cranberry-mix.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165423.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165423.jpg",
    "stock": null
  },
  {
    "id": 4015,
    "sharedProductId": "gv-chocolate-peanut-mix",
    "n": "Great Value Chocolate Peanut Butter",
    "d": "Trail Mix · 624 g",
    "c": "Frutos secos",
    "p": 13500,
    "currency": "CUP",
    "img": "/products/real/gv-chocolate-peanut-mix.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165423.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165423.jpg",
    "stock": null
  },
  {
    "id": 4016,
    "sharedProductId": "gv-probiotic-mix",
    "n": "Great Value Probiotic Trail Mix",
    "d": "Bolsa de 680 g",
    "c": "Frutos secos",
    "p": 13000,
    "currency": "CUP",
    "img": "/products/real/gv-probiotic-mix.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165423.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165423.jpg",
    "stock": null
  },
  {
    "id": 4017,
    "sharedProductId": "members-pistachios",
    "n": "Pistachos Member’s Mark",
    "d": "Roasted California · Sea Salt · 1,36 kg",
    "c": "Frutos secos",
    "p": 35000,
    "currency": "CUP",
    "img": "/products/real/members-pistachios.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165430.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165430.jpg",
    "stock": null
  },
  {
    "id": 4018,
    "sharedProductId": "wonderful-pistachios-454",
    "n": "Pistachos Wonderful sin cáscara",
    "d": "Roasted & Salted · Bolsa de 454 g",
    "c": "Frutos secos",
    "p": 25500,
    "currency": "CUP",
    "img": "/products/real/wonderful-pistachios-454.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165430.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165430.jpg",
    "stock": null
  },
  {
    "id": 4019,
    "sharedProductId": "wonderful-pistachios-340",
    "n": "Pistachos Wonderful sin cáscara",
    "d": "Roasted & Salted · Bolsa de 340 g",
    "c": "Frutos secos",
    "p": 18000,
    "currency": "CUP",
    "img": "/products/real/wonderful-pistachios-340.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165430.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165430.jpg",
    "stock": null
  },
  {
    "id": 4020,
    "sharedProductId": "wonderful-pepper",
    "n": "Pistachos Wonderful Sea Salt & Pepper",
    "d": "Sin cáscara · Bolsa de 311 g",
    "c": "Frutos secos",
    "p": 18000,
    "currency": "CUP",
    "img": "/products/real/wonderful-pepper.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165430.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165430.jpg",
    "stock": null
  },
  {
    "id": 5001,
    "sharedProductId": "barilla-pesto",
    "n": "Pesto Barilla alla Genovese",
    "d": "Frasco · Albahaca",
    "c": "Conservas",
    "p": 2500,
    "currency": "CUP",
    "img": "/products/real/barilla-pesto.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165913.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165913.jpg",
    "stock": null
  },
  {
    "id": 5002,
    "sharedProductId": "trader-olive-pesto",
    "n": "Trader Joe’s Olive and Basil Pesto",
    "d": "Frasco de 180 g",
    "c": "Conservas",
    "p": 4200,
    "currency": "CUP",
    "img": "/products/real/trader-olive-pesto.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165913.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165913.jpg",
    "stock": null
  },
  {
    "id": 5003,
    "sharedProductId": "trader-basil-pesto",
    "n": "Trader Joe’s Basil Pesto Sauce",
    "d": "Frasco de 190 g",
    "c": "Conservas",
    "p": 4700,
    "currency": "CUP",
    "img": "/products/real/trader-basil-pesto.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165916.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165916.jpg",
    "stock": null
  },
  {
    "id": 5004,
    "sharedProductId": "huerta-pepinos",
    "n": "Pepinos grandes La Huerta de al Lado",
    "d": "En vinagre · Frasco",
    "c": "Conservas",
    "p": 1700,
    "currency": "CUP",
    "img": "/products/real/huerta-pepinos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165916.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165916.jpg",
    "stock": null
  },
  {
    "id": 5005,
    "sharedProductId": "huerta-cocktail",
    "n": "Cóctel de encurtidos La Huerta de al Lado",
    "d": "345 g · Peso escurrido 180 g",
    "c": "Conservas",
    "p": 1700,
    "currency": "CUP",
    "img": "/products/real/huerta-cocktail.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165920.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165920.jpg",
    "stock": null
  },
  {
    "id": 5006,
    "sharedProductId": "huerta-banderillas",
    "n": "Banderillas La Huerta de al Lado",
    "d": "Frasco de encurtidos en pinchos",
    "c": "Conservas",
    "p": 1700,
    "currency": "CUP",
    "img": "/products/real/huerta-banderillas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165920.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165920.jpg",
    "stock": null
  },
  {
    "id": 5007,
    "sharedProductId": "vima-negras",
    "n": "Aceitunas negras sin hueso Vima",
    "d": "Contenido neto 1.820 g · Escurrido 930 g",
    "c": "Conservas",
    "p": 13000,
    "currency": "CUP",
    "img": "/products/real/vima-negras.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165924.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165924.jpg",
    "stock": null
  },
  {
    "id": 5008,
    "sharedProductId": "vima-alinadas",
    "n": "Aceitunas verdes aliñadas Vima",
    "d": "Frasco grande",
    "c": "Conservas",
    "p": 12500,
    "currency": "CUP",
    "img": "/products/real/vima-alinadas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165928.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165928.jpg",
    "stock": null
  },
  {
    "id": 5009,
    "sharedProductId": "qbanito-cebollitas",
    "n": "Cebollitas Qbanito",
    "d": "Contenido neto 230 g · Escurrido 120 g",
    "c": "Conservas",
    "p": 1600,
    "currency": "CUP",
    "img": "/products/real/qbanito-cebollitas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165932.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165932.jpg",
    "stock": null
  },
  {
    "id": 5010,
    "sharedProductId": "didi-peras",
    "n": "Peras Didi en almíbar ligero",
    "d": "Mitades · Lata",
    "c": "Conservas",
    "p": 700,
    "currency": "CUP",
    "img": "/products/real/didi-peras.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165932.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165932.jpg",
    "stock": null
  },
  {
    "id": 5011,
    "sharedProductId": "tom-frijol-cocido",
    "n": "Frijoles colorados cocidos Tom Food",
    "d": "Lata",
    "c": "Conservas",
    "p": 1750,
    "currency": "CUP",
    "img": "/products/real/tom-frijol-cocido.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165935.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165935.jpg",
    "stock": null
  },
  {
    "id": 5012,
    "sharedProductId": "fairhill-maiz",
    "n": "Maíz dulce Fairhill Farms",
    "d": "Whole Kernel · Lata de 432 g",
    "c": "Conservas",
    "p": 1800,
    "currency": "CUP",
    "img": "/products/real/fairhill-maiz.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165935.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165935.jpg",
    "stock": null
  },
  {
    "id": 5013,
    "sharedProductId": "fairhill-vegetales",
    "n": "Vegetales mixtos Fairhill Farms",
    "d": "Mixed Vegetables · Lata de 425 g",
    "c": "Conservas",
    "p": 1450,
    "currency": "CUP",
    "img": "/products/real/fairhill-vegetales.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165940.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165940.jpg",
    "stock": null
  },
  {
    "id": 5014,
    "sharedProductId": "fairhill-frutas",
    "n": "Cóctel de frutas Fairhill Farms",
    "d": "En jugo de fruta · Lata de 425 g",
    "c": "Conservas",
    "p": 2300,
    "currency": "CUP",
    "img": "/products/real/fairhill-frutas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165940.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165940.jpg",
    "stock": null
  },
  {
    "id": 5015,
    "sharedProductId": "delcampo-colorados",
    "n": "Frijoles colorados Del Campo",
    "d": "Bolsa de 1 lb",
    "c": "Alimentos",
    "p": 1600,
    "currency": "CUP",
    "img": "/products/real/delcampo-colorados.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165949.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165949.jpg",
    "stock": null
  },
  {
    "id": 5016,
    "sharedProductId": "energy-negros",
    "n": "Frijoles negros Energy",
    "d": "Bolsa de 1 kg",
    "c": "Alimentos",
    "p": 1300,
    "currency": "CUP",
    "img": "/products/real/energy-negros.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165953.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165953.jpg",
    "stock": null
  },
  {
    "id": 5017,
    "sharedProductId": "happyone-adulto",
    "n": "Alimento para perros HappyOne Adulto",
    "d": "Con pollo · Bolsa de 4 kg",
    "c": "Mascotas",
    "p": 18700,
    "currency": "CUP",
    "img": "/products/real/happyone-adulto.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_171633.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_171633.jpg",
    "stock": null
  },
  {
    "id": 6001,
    "sharedProductId": "coca-cola-355",
    "n": "Coca-Cola Original",
    "d": "Lata de 355 mL",
    "c": "Bebidas",
    "p": 1200,
    "currency": "CUP",
    "img": "/products/real/coca-cola-355.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165625.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165625.jpg",
    "stock": null
  },
  {
    "id": 6002,
    "sharedProductId": "koffio-vainilla",
    "n": "Café con leche Koffo Vanilla",
    "d": "Lata · Vainilla",
    "c": "Bebidas",
    "p": 500,
    "currency": "CUP",
    "img": "/products/real/koffio-vainilla.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165627_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165627_1.jpg",
    "stock": null
  },
  {
    "id": 6003,
    "sharedProductId": "pepsi-lata",
    "n": "Pepsi",
    "d": "Lata",
    "c": "Bebidas",
    "p": 1150,
    "currency": "CUP",
    "img": "/products/real/pepsi-lata.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165627_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165627_1.jpg",
    "stock": null
  },
  {
    "id": 6004,
    "sharedProductId": "tigon-energy",
    "n": "Tigon Energy Drink",
    "d": "Lata",
    "c": "Bebidas",
    "p": 1000,
    "currency": "CUP",
    "img": "/products/real/tigon-energy.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165627_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165627_1.jpg",
    "stock": null
  },
  {
    "id": 6005,
    "sharedProductId": "kurtz-mayonesa",
    "n": "Mayonesa Kurtz Real",
    "d": "Frasco de 887 mL",
    "c": "Alimentos",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/kurtz-mayonesa.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165856_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165856_1.jpg",
    "stock": null
  },
  {
    "id": 6006,
    "sharedProductId": "hollandpark-mayonesa",
    "n": "Mayonesa HollandPark",
    "d": "Frasco",
    "c": "Alimentos",
    "p": 3000,
    "currency": "CUP",
    "img": "/products/real/hollandpark-mayonesa.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165856_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165856_1.jpg",
    "stock": null
  },
  {
    "id": 6007,
    "sharedProductId": "ayala-mayonesa",
    "n": "Mayonesa Ayala Tradicional",
    "d": "Frasco · Sabor tradicional",
    "c": "Alimentos",
    "p": 2650,
    "currency": "CUP",
    "img": "/products/real/ayala-mayonesa.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165853_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165853_1.jpg",
    "stock": null
  },
  {
    "id": 6008,
    "sharedProductId": "jolyni-spaghetti",
    "n": "Espaguetis Jolyni",
    "d": "Bolsa de 450 g",
    "c": "Alimentos",
    "p": 600,
    "currency": "CUP",
    "img": "/products/real/jolyni-spaghetti.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165656.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165656.jpg",
    "stock": null
  },
  {
    "id": 6009,
    "sharedProductId": "primo-linguine",
    "n": "Linguine Primo",
    "d": "Bolsa de 900 g",
    "c": "Alimentos",
    "p": 1050,
    "currency": "CUP",
    "img": "/products/real/primo-linguine.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165714.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165714.jpg",
    "stock": null
  },
  {
    "id": 6010,
    "sharedProductId": "italpasta-pennine",
    "n": "Pennine Rigate Italpasta",
    "d": "Bolsa de 900 g",
    "c": "Alimentos",
    "p": 1050,
    "currency": "CUP",
    "img": "/products/real/italpasta-pennine.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165741.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165741.jpg",
    "stock": null
  },
  {
    "id": 6011,
    "sharedProductId": "socheezy-macaroni",
    "n": "Macarrones con queso So Cheezy",
    "d": "Original · Caja de 206 g",
    "c": "Alimentos",
    "p": 1050,
    "currency": "CUP",
    "img": "/products/real/socheezy-macaroni.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165824_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165824_1.jpg",
    "stock": null
  },
  {
    "id": 6012,
    "sharedProductId": "aldaketa-mostaza",
    "n": "Mostaza Aldaketa",
    "d": "Botella",
    "c": "Alimentos",
    "p": 1500,
    "currency": "CUP",
    "img": "/products/real/aldaketa-mostaza.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165830.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165830.jpg",
    "stock": null
  },
  {
    "id": 6013,
    "sharedProductId": "azotea-mostaza",
    "n": "Mostaza Azotea Original",
    "d": "Botella",
    "c": "Alimentos",
    "p": 2000,
    "currency": "CUP",
    "img": "/products/real/azotea-mostaza.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165830.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165830.jpg",
    "stock": null
  },
  {
    "id": 6014,
    "sharedProductId": "kurtz-mostaza",
    "n": "Mostaza Kurtz Yellow",
    "d": "Botella de 567 g",
    "c": "Alimentos",
    "p": 1400,
    "currency": "CUP",
    "img": "/products/real/kurtz-mostaza.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165830.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165830.jpg",
    "stock": null
  },
  {
    "id": 6015,
    "sharedProductId": "vima-mostaza",
    "n": "Mostaza Vima",
    "d": "Botella de 1.850 g",
    "c": "Alimentos",
    "p": 4300,
    "currency": "CUP",
    "img": "/products/real/vima-mostaza.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165830.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165830.jpg",
    "stock": null
  },
  {
    "id": 6016,
    "sharedProductId": "kurtz-italian",
    "n": "Aderezo Kurtz Zesty Italian",
    "d": "Botella",
    "c": "Alimentos",
    "p": 2300,
    "currency": "CUP",
    "img": "/products/real/kurtz-italian.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165834.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165834.jpg",
    "stock": null
  },
  {
    "id": 6017,
    "sharedProductId": "bullseye-original",
    "n": "Salsa BBQ Bull’s-Eye Everyday",
    "d": "Original · Botella de 507 g",
    "c": "Alimentos",
    "p": 6000,
    "currency": "CUP",
    "img": "/products/real/bullseye-original.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165834.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165834.jpg",
    "stock": null
  },
  {
    "id": 6018,
    "sharedProductId": "burmans-spicybrown",
    "n": "Mostaza Burman’s Spicy Brown",
    "d": "Botella de 340 g",
    "c": "Alimentos",
    "p": 2200,
    "currency": "CUP",
    "img": "/products/real/burmans-spicybrown.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165834.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165834.jpg",
    "stock": null
  },
  {
    "id": 6019,
    "sharedProductId": "jade-soya",
    "n": "Salsa de soya Jade Dragon",
    "d": "Botella de 356 mL",
    "c": "Alimentos",
    "p": 2200,
    "currency": "CUP",
    "img": "/products/real/jade-soya.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165846.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165846.jpg",
    "stock": null
  },
  {
    "id": 6020,
    "sharedProductId": "sakura-soya",
    "n": "Salsa de soya Sakura Tradicional",
    "d": "Botella de 500 mL",
    "c": "Alimentos",
    "p": 1000,
    "currency": "CUP",
    "img": "/products/real/sakura-soya.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165846.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165846.jpg",
    "stock": null
  },
  {
    "id": 6021,
    "sharedProductId": "castelo-italiano",
    "n": "Aderezo Castelo Italiano",
    "d": "Botella de 236 mL",
    "c": "Alimentos",
    "p": 700,
    "currency": "CUP",
    "img": "/products/real/castelo-italiano.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165840.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165840.jpg",
    "stock": null
  },
  {
    "id": 6022,
    "sharedProductId": "countrybarn-french",
    "n": "Aderezo Country Barn French",
    "d": "Botella de 473 mL",
    "c": "Alimentos",
    "p": 1750,
    "currency": "CUP",
    "img": "/products/real/countrybarn-french.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165840.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165840.jpg",
    "stock": null
  },
  {
    "id": 6023,
    "sharedProductId": "burmans-dill-mayo",
    "n": "Aderezo de mayonesa Burman’s Dill",
    "d": "Botella de 354 mL",
    "c": "Alimentos",
    "p": 5500,
    "currency": "CUP",
    "img": "/products/real/burmans-dill-mayo.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165851.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165851.jpg",
    "stock": null
  },
  {
    "id": 6024,
    "sharedProductId": "friend-brava",
    "n": "Salsa Brava Friend Cook",
    "d": "Botella de 330 mL",
    "c": "Alimentos",
    "p": 1800,
    "currency": "CUP",
    "img": "/products/real/friend-brava.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165851.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165851.jpg",
    "stock": null
  },
  {
    "id": 6025,
    "sharedProductId": "friend-barbacoa",
    "n": "Salsa Barbacoa Friend Cook",
    "d": "Grill Texas BBQ · Botella de 330 mL",
    "c": "Alimentos",
    "p": 2000,
    "currency": "CUP",
    "img": "/products/real/friend-barbacoa.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165851.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165851.jpg",
    "stock": null
  },
  {
    "id": 6026,
    "sharedProductId": "trader-truffle-aioli",
    "n": "Alioli de trufa Trader Joe’s",
    "d": "Vegan · Frasco de 285 g",
    "c": "Alimentos",
    "p": 7000,
    "currency": "CUP",
    "img": "/products/real/trader-truffle-aioli.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165853_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165853_1.jpg",
    "stock": null
  },
  {
    "id": 6027,
    "sharedProductId": "kurtz-relish",
    "n": "Kurtz Sweet Relish",
    "d": "Frasco de 473 mL",
    "c": "Conservas",
    "p": 1550,
    "currency": "CUP",
    "img": "/products/real/kurtz-relish.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165853_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165853_1.jpg",
    "stock": null
  },
  {
    "id": 6028,
    "sharedProductId": "huerta-alcaparras",
    "n": "Alcaparras La Huerta de al Lado",
    "d": "En vinagre · Frasco",
    "c": "Conservas",
    "p": 1600,
    "currency": "CUP",
    "img": "/products/real/huerta-alcaparras.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165910.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165910.jpg",
    "stock": null
  },
  {
    "id": 6029,
    "sharedProductId": "lasota-alcaparras",
    "n": "Alcaparras La Sota",
    "d": "Contenido neto 100 g · Escurrido 60 g",
    "c": "Conservas",
    "p": 1600,
    "currency": "CUP",
    "img": "/products/real/lasota-alcaparras.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165910.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165910.jpg",
    "stock": null
  },
  {
    "id": 7001,
    "sharedProductId": "homebright-verde",
    "n": "Perlas aromáticas Homebright Moonlight Fresh",
    "d": "Moonlight Fresh · Perlas aromáticas para lavandería",
    "c": "Aseo",
    "p": 4400,
    "currency": "CUP",
    "img": "/products/real/homebright-verde.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 7002,
    "sharedProductId": "delcampo-lentejas",
    "n": "Lentejas Del Campo",
    "d": "Bolsa · Lentejas secas",
    "c": "Alimentos",
    "p": 1400,
    "currency": "CUP",
    "img": "/products/real/delcampo-lentejas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165959.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165959.jpg",
    "stock": null
  },
  {
    "id": 7003,
    "sharedProductId": "delcampo-negros",
    "n": "Frijoles negros Del Campo",
    "d": "Bolsa de1lb · Frijoles negros secos",
    "c": "Alimentos",
    "p": 1600,
    "currency": "CUP",
    "img": "/products/real/delcampo-negros.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165949.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165949.jpg",
    "stock": null
  }
];
