// CATÁLOGO PROVISIONAL BLOQUE 1
// Datos e imágenes reutilizados temporalmente de Mercado 23 y 28 para validar UX.
// Sustituir por inventario real de Frutos Secos Colo antes de producción comercial.
export const products=[
{id:1,n:"Hamburguesas congeladas",d:"Karmac · Paquete 500 g · 6 unidades",c:"Carnes y Embutidos",p:780,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/hamburguesas-congeladas.webp"},
{id:2,n:"Albóndigas congeladas",d:"Karmac · Bolsa",c:"Carnes y Embutidos",p:7300,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/albondigas-congeladas.webp"},
{id:3,n:"Carne de cerdo",d:"Bandeja",c:"Carnes y Embutidos",p:3500,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/cerdo-bandeja.webp"},
{id:4,n:"Carne de cerdo",d:"Bandeja grande",c:"Carnes y Embutidos",p:4900,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/cerdo-bandeja-grande.webp"},
{id:8,n:"Embutido largo",d:"Pieza",c:"Carnes y Embutidos",p:5200,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/embutido-largo.webp"},
{id:9,n:"Salchichón",d:"Pieza en lonchas",c:"Carnes y Embutidos",p:3800,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/salchichon.webp"},
{id:10,n:"Jamonada / mortadela",d:"Pieza",c:"Carnes y Embutidos",p:4600,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jamonada.webp"},
{id:17,n:"Néctar Tropical",d:"Goliath · Cartón 1 L",c:"Bebidas",p:1500,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/nectar-tropical.webp"},
{id:18,n:"Néctar de guayaba",d:"Goliath · Cartón 1 L",c:"Bebidas",p:1500,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/nectar-guayaba.webp"},
{id:19,n:"Néctar de piña",d:"Goliath · Cartón 1 L",c:"Bebidas",p:1500,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/nectar-pina.webp"},
{id:20,n:"Jugo de naranja",d:"La Estancia · Cartón 200 mL",c:"Bebidas",p:370,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jugo-estancia-naranja.webp"},
{id:60,n:"Néctar de guayaba pequeño",d:"La Estancia · Cartón 200 mL",c:"Bebidas",p:370,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jugo-estancia-guayaba.webp"},
{id:21,n:"Jugo Tropical",d:"Mozo Juice · Cartón 200 mL",c:"Bebidas",p:290,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jugo-mozo-tropical.webp"},
{id:61,n:"Jugo de mango",d:"Mozo Juice · Cartón 200 mL",c:"Bebidas",p:290,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jugo-mozo-mango.webp"},
{id:62,n:"Bebida de frutas sabor rojo",d:"Mozo Juice · Cartón 200 mL",c:"Bebidas",p:290,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jugo-mozo-rojo.webp"},
{id:38,n:"Jamón cocido en lata",d:"Iberia · Lata",c:"Despensa y Conservas",p:6000,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/jamon-lata.webp"},
{id:41,n:"Lentejas",d:"Peñalba · Bolsa 500 g",c:"Despensa y Conservas",p:850,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/lentejas.webp"},
{id:42,n:"Frijoles blancos",d:"Peñalba · Bolsa",c:"Despensa y Conservas",p:800,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/frijoles-blancos.webp"},
{id:43,n:"Frijoles negros",d:"Peñalba · Bolsa 500 g",c:"Despensa y Conservas",p:850,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/frijoles-negros.webp"},
{id:45,n:"Aceitunas verdes",d:"Benimar · Lata 2,35 kg",c:"Despensa y Conservas",p:9900,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/aceitunas-verdes.webp"},
{id:46,n:"Champiñones en conserva",d:"Celorrio · Lata",c:"Despensa y Conservas",p:1300,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/champinones-lata.webp"},
{id:47,n:"Cinnamon Crisps",d:"Gullón · Caja 200 g",c:"Snacks y Dulces",p:1900,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/cinnamon-crisps.webp"},
{id:63,n:"Papas fritas Lay's",d:"Clásicas · Bolsa 170 g",c:"Snacks y Dulces",p:1500,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/papas-lays.webp"},
{id:51,n:"Galletas Oli surtidas",d:"Caja 15 g · sabores variados",c:"Snacks y Dulces",p:1150,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/oli-surtidas.webp"},
{id:52,n:"Caramelos Mint",d:"Fiesta · Bolsa",c:"Snacks y Dulces",p:2700,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/caramelos-mint.webp"},
{id:53,n:"Caramelos Éclair",d:"Frutika · Bolsa",c:"Snacks y Dulces",p:2700,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/caramelos-eclair.webp"},
{id:54,n:"Cappuccino Candy",d:"Fiesta · Bolsa",c:"Snacks y Dulces",p:2700,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/cappuccino-candy.webp"},
{id:55,n:"Butter Milky Candy",d:"Ricolino · Bolsa",c:"Snacks y Dulces",p:2700,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/butter-milky-candy.webp"},
{id:56,n:"Coffee Candy",d:"Richto · Bolsa",c:"Snacks y Dulces",p:2700,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/coffee-candy.webp"},
{id:57,n:"Chocolate Milka",d:"Tableta",c:"Snacks y Dulces",p:2200,img:"https://raw.githubusercontent.com/ernest196391/23-y-28-/main/public/products/chocolate-milka.webp"}
];
