// Inventario real: precios CUP confirmados por el propietario el 2026-10-04.
// IDs nuevos evitan que carritos del catálogo provisional cambien de producto.
export const products=[
  {
    "id": 1001,
    "sharedProductId": "almendras-chocolate",
    "n": "Almendras con chocolate con leche",
    "d": "Member’s Mark · Frasco 1,36 kg",
    "c": "Frutos secos",
    "p": 25500,
    "currency": "CUP",
    "img": "/products/real/almendras-chocolate.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164901.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164901.jpg",
    "stock": null
  },
  {
    "id": 1002,
    "sharedProductId": "pasas-chocolate",
    "n": "Pasas cubiertas de chocolate",
    "d": "Member’s Mark · Frasco 1,53 kg",
    "c": "Frutos secos",
    "p": 24500,
    "currency": "CUP",
    "img": "/products/real/pasas-chocolate.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164902_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164902_1.jpg",
    "stock": null
  },
  {
    "id": 1003,
    "sharedProductId": "pobeda-madagascar",
    "n": "Chocolate Pobeda Madagascar",
    "d": "Chocolate negro · 55 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3300,
    "currency": "CUP",
    "img": "/products/real/pobeda-madagascar.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164905_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164905_1.jpg",
    "stock": null
  },
  {
    "id": 1004,
    "sharedProductId": "pobeda-ecuador",
    "n": "Chocolate Pobeda Ecuador",
    "d": "Chocolate con leche · 45 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3500,
    "currency": "CUP",
    "img": "/products/real/pobeda-ecuador.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164905_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164905_1.jpg",
    "stock": null
  },
  {
    "id": 1005,
    "sharedProductId": "pobeda-cote-ivoire",
    "n": "Chocolate Pobeda Côte d’Ivoire",
    "d": "Chocolate negro · 60 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3700,
    "currency": "CUP",
    "img": "/products/real/pobeda-cote-ivoire.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164905_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164905_1.jpg",
    "stock": null
  },
  {
    "id": 1006,
    "sharedProductId": "lacasa-menta",
    "n": "Chocolate negro con menta Lacasa",
    "d": "70 % cacao · Tableta",
    "c": "Alimentos",
    "p": 3900,
    "currency": "CUP",
    "img": "/products/real/lacasa-menta.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164907_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164907_1.jpg",
    "stock": null
  },
  {
    "id": 1007,
    "sharedProductId": "bentons-fresa",
    "n": "Mini galletas Benton's de fresa",
    "d": "Strawberry Mini Fudge Dipped Cookie Bites · Bolsa",
    "c": "Alimentos",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/bentons-fresa.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164913_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164913_1.jpg",
    "stock": null
  },
  {
    "id": 1008,
    "sharedProductId": "bentons-arandano",
    "n": "Mini galletas Benton's de arándano y limón",
    "d": "Blueberry Lemon Mini Fudge Dipped Cookie Bites · Bolsa",
    "c": "Alimentos",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/bentons-arandano.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164913_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164913_1.jpg",
    "stock": null
  },
  {
    "id": 1009,
    "sharedProductId": "choceur-cups",
    "n": "Chocolate Choceur con mantequilla de maní",
    "d": "Milk Chocolate Peanut Butter Cups · Bolsa",
    "c": "Alimentos",
    "p": 5600,
    "currency": "CUP",
    "img": "/products/real/choceur-cups.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164915_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164915_1.jpg",
    "stock": null
  },
  {
    "id": 1010,
    "sharedProductId": "mounds",
    "n": "Chocolates Mounds de coco",
    "d": "Paquete de 4 barras snacksize",
    "c": "Alimentos",
    "p": 2500,
    "currency": "CUP",
    "img": "/products/real/mounds.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164918_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164918_1.jpg",
    "stock": null
  },
  {
    "id": 1011,
    "sharedProductId": "milky-way",
    "n": "Chocolate Milky Way",
    "d": "Chocolate con leche, caramelo y nougat · 48 g",
    "c": "Alimentos",
    "p": 2500,
    "currency": "CUP",
    "img": "/products/real/milky-way.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164921.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164921.jpg",
    "stock": null
  },
  {
    "id": 1012,
    "sharedProductId": "papel-excelencia",
    "n": "Papel higiénico La Excelencia",
    "d": "Super Suave · 4 rollos · 2 capas",
    "c": "Aseo",
    "p": 1250,
    "currency": "CUP",
    "img": "/products/real/papel-excelencia.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164927_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164927_1.jpg",
    "stock": null
  },
  {
    "id": 1013,
    "sharedProductId": "members-pacs",
    "n": "Cápsulas de detergente Member's Mark",
    "d": "Laundry Power Pacs · Blooming Breeze · 65 unidades",
    "c": "Aseo",
    "p": 21000,
    "currency": "CUP",
    "img": "/products/real/members-pacs.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164933.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164933.jpg",
    "stock": null
  },
  {
    "id": 1014,
    "sharedProductId": "tide-spring",
    "n": "Cápsulas de detergente Tide Spring Meadow",
    "d": "Pods · Bolsa",
    "c": "Aseo",
    "p": 19000,
    "currency": "CUP",
    "img": "/products/real/tide-spring.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164936_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164936_1.jpg",
    "stock": null
  },
  {
    "id": 1015,
    "sharedProductId": "gain-original-grande",
    "n": "Cápsulas de detergente Gain Original",
    "d": "Bolsa grande · Vista del envase disponible",
    "c": "Aseo",
    "p": 18700,
    "currency": "CUP",
    "img": "/products/real/gain-original-grande.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164936_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164936_1.jpg",
    "stock": null
  },
  {
    "id": 1016,
    "sharedProductId": "tide-oxi",
    "n": "Cápsulas Tide Ultra Oxi",
    "d": "Power Pods · Bolsa 757 g",
    "c": "Aseo",
    "p": 9000,
    "currency": "CUP",
    "img": "/products/real/tide-oxi.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164939.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164939.jpg",
    "stock": null
  },
  {
    "id": 1017,
    "sharedProductId": "gain-suavizante",
    "n": "Suavizante Gain Original",
    "d": "Fabric Softener · 306 mL",
    "c": "Aseo",
    "p": 5000,
    "currency": "CUP",
    "img": "/products/real/gain-suavizante.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164949_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164949_1.jpg",
    "stock": null
  },
  {
    "id": 1018,
    "sharedProductId": "magali-mora",
    "n": "Gel de baño Magali Mora",
    "d": "Blackberry · Botella",
    "c": "Aseo",
    "p": 2300,
    "currency": "CUP",
    "img": "/products/real/magali-mora.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164957_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164957_1.jpg",
    "stock": null
  },
  {
    "id": 1019,
    "sharedProductId": "snonas-candy",
    "n": "Gel de baño S'nonas Candy Shop",
    "d": "Botella",
    "c": "Aseo",
    "p": 3300,
    "currency": "CUP",
    "img": "/products/real/snonas-candy.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164957_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164957_1.jpg",
    "stock": null
  },
  {
    "id": 1020,
    "sharedProductId": "snonas-honey",
    "n": "Colonia S'nonas Fraîche amarilla",
    "d": "Botella 750 mL",
    "c": "Aseo",
    "p": 3300,
    "currency": "CUP",
    "img": "/products/real/snonas-honey.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_164957_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_164957_1.jpg",
    "stock": null
  },
  {
    "id": 1021,
    "sharedProductId": "dicora-avena",
    "n": "Gel de baño Dicora Yogurt y Avena",
    "d": "Urban Fit · Shower Cream · 400 mL",
    "c": "Aseo",
    "p": 4200,
    "currency": "CUP",
    "img": "/products/real/dicora-avena.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1022,
    "sharedProductId": "dicora-citrus",
    "n": "Gel de baño Dicora Citrus y Peach",
    "d": "Urban Fit · 400 mL",
    "c": "Aseo",
    "p": 4200,
    "currency": "CUP",
    "img": "/products/real/dicora-citrus.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1023,
    "sharedProductId": "snonas-body",
    "n": "Crema corporal S'nonas PH",
    "d": "Body Milk Hidratante · 1.000 mL",
    "c": "Aseo",
    "p": 3350,
    "currency": "CUP",
    "img": "/products/real/snonas-body.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1024,
    "sharedProductId": "snonas-coco-pina",
    "n": "Gel de baño S'nonas Coco y Piña",
    "d": "Botella 750 mL",
    "c": "Aseo",
    "p": 3850,
    "currency": "CUP",
    "img": "/products/real/snonas-coco-pina.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165004.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165004.jpg",
    "stock": null
  },
  {
    "id": 1025,
    "sharedProductId": "peine-flexys",
    "n": "Peine antipiojos Flexys",
    "d": "Peine de doble cara · 1 unidad",
    "c": "Aseo",
    "p": 1000,
    "currency": "CUP",
    "img": "/products/real/peine-flexys.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165013_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165013_1.jpg",
    "stock": null
  },
  {
    "id": 1026,
    "sharedProductId": "balsamos-paul-frank",
    "n": "Bálsamos labiales Paul Frank",
    "d": "Set de 6 piezas",
    "c": "Aseo",
    "p": 2000,
    "currency": "CUP",
    "img": "/products/real/balsamos-paul-frank.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165016_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165016_1.jpg",
    "stock": null
  },
  {
    "id": 1027,
    "sharedProductId": "ventilador-pure-silk",
    "n": "Mini ventilador Pure Silk",
    "d": "Portátil · Funciona con pilas",
    "c": "Accesorios",
    "p": 4800,
    "currency": "CUP",
    "img": "/products/real/ventilador-pure-silk.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165019_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165019_1.jpg",
    "stock": null
  },
  {
    "id": 1028,
    "sharedProductId": "nordic-ar",
    "n": "Perlas aromáticas Nordic Air",
    "d": "In-wash Fragrance Booster · 297 g",
    "c": "Aseo",
    "p": 4500,
    "currency": "CUP",
    "img": "/products/real/nordic-ar.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1029,
    "sharedProductId": "un-n09",
    "n": "Perlas aromáticas Un N.09",
    "d": "Laundry Scent Booster · Fine Pine",
    "c": "Aseo",
    "p": 7500,
    "currency": "CUP",
    "img": "/products/real/un-n09.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1030,
    "sharedProductId": "ohmy-azul",
    "n": "Champú Oh My azul",
    "d": "Antiqueda · 300 mL",
    "c": "Aseo",
    "p": 3450,
    "currency": "CUP",
    "img": "/products/real/ohmy-azul.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1031,
    "sharedProductId": "ohmy-rojo",
    "n": "Champú Oh My rojo",
    "d": "Desmaia · 300 mL",
    "c": "Aseo",
    "p": 3450,
    "currency": "CUP",
    "img": "/products/real/ohmy-rojo.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "id": 1032,
    "sharedProductId": "febreze-luxe",
    "n": "Ambientador Febreze Luxe",
    "d": "Air · Summer Golden Hour",
    "c": "Aseo",
    "p": 6000,
    "currency": "CUP",
    "img": "/products/real/febreze-luxe.webp",
    "provisional": false,
    "source": "store-photo",
    "sourcePhoto": "IMG_20261009_165026_1.jpg",
    "sourceImage": "/catalog-sources/IMG_20261009_165026_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "salud-salfuman",
    "n": "Aguafuerte La Salud Salfumán",
    "d": "Botella negra · Cierre blanco",
    "c": "Aseo",
    "p": 2900,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165036.jpg",
    "id": 2001,
    "img": "/products/real/salud-salfuman.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165036.jpg",
    "stock": null
  },
  {
    "sharedProductId": "salud-multiusos",
    "n": "Multiusos y limpiacristales La Salud",
    "d": "2 en 1 · Botella de líquido azul",
    "c": "Aseo",
    "p": 2900,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165039_1.jpg",
    "id": 2002,
    "img": "/products/real/salud-multiusos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165039_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "salud-antical-spray",
    "n": "Antical La Salud Brillo Total",
    "d": "2 en 1 · Baños y duchas · Pulverizador",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165039_1.jpg",
    "id": 2003,
    "img": "/products/real/salud-antical-spray.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165039_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "khawla-lavavajillas",
    "n": "Lavavajillas Khawla",
    "d": "Botella blanca · Tapón verde",
    "c": "Aseo",
    "p": 1200,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165045.jpg",
    "id": 2004,
    "img": "/products/real/khawla-lavavajillas.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165045.jpg",
    "stock": null
  },
  {
    "sharedProductId": "dawn-crisp-lilac",
    "n": "Lavavajillas Dawn Powerwash Crisp Lilac",
    "d": "Recarga · 16 oz",
    "c": "Aseo",
    "p": 21500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165050_1.jpg",
    "id": 2005,
    "img": "/products/real/dawn-crisp-lilac.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165050_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "lex-wc-limp",
    "n": "Limpiador Lex Clean WC Limp",
    "d": "Desincrustante · 1 litro",
    "c": "Aseo",
    "p": 4900,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165055_1.jpg",
    "id": 2006,
    "img": "/products/real/lex-wc-limp.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165055_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "pano-blanco",
    "n": "Paño de limpieza blanco",
    "d": "Unidad · Medidas por confirmar",
    "c": "Aseo",
    "p": 700,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165059_1.jpg",
    "id": 2007,
    "img": "/products/real/pano-blanco.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165059_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "pano-amarillo",
    "n": "Paño de limpieza amarillo",
    "d": "Unidad · Medidas por confirmar",
    "c": "Aseo",
    "p": 1150,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165059_1.jpg",
    "id": 2008,
    "img": "/products/real/pano-amarillo.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165059_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "nature-cinnamon",
    "n": "Enjuague bucal Nature Fresh Cinnamon",
    "d": "532 mL",
    "c": "Aseo",
    "p": 4000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165106_1.jpg",
    "id": 2009,
    "img": "/products/real/nature-cinnamon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165106_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "nature-spearmint",
    "n": "Enjuague bucal Nature Fresh Spearmint",
    "d": "710 mL",
    "c": "Aseo",
    "p": 4500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165106_1.jpg",
    "id": 2010,
    "img": "/products/real/nature-spearmint.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165106_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "mister-pack-congelacion",
    "n": "Bolsas para congelación Mister Pack",
    "d": "15 bolsas · 28 × 42 cm · 6 L",
    "c": "Aseo",
    "p": 1000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165110_1.jpg",
    "id": 2011,
    "img": "/products/real/mister-pack-congelacion.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165110_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "mical-film",
    "n": "Film transparente Mical",
    "d": "Rollo de 30 m",
    "c": "Aseo",
    "p": 2500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165106_1.jpg",
    "id": 2012,
    "img": "/products/real/mical-film.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165106_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "alfa-molinillos",
    "n": "Molinillos de sal y pimienta Alfa",
    "d": "Set de 2 piezas · Verde",
    "c": "Accesorios",
    "p": 4400,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165114.jpg",
    "id": 2013,
    "img": "/products/real/alfa-molinillos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165114.jpg",
    "stock": null
  },
  {
    "sharedProductId": "summers-eve-fresh",
    "n": "Summer’s Eve Fresh Scent",
    "d": "Caja · Presentación visible",
    "c": "Aseo",
    "p": 1350,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165120.jpg",
    "id": 2014,
    "img": "/products/real/summers-eve-fresh.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165120.jpg",
    "stock": null
  },
  {
    "sharedProductId": "vapour-rub",
    "n": "Vapour Rub Green Stick",
    "d": "Frasco · Family Value Pack",
    "c": "Aseo",
    "p": 1100,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165120.jpg",
    "id": 2015,
    "img": "/products/real/vapour-rub.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165120.jpg",
    "stock": null
  },
  {
    "sharedProductId": "bastoncillos-grandes",
    "n": "Bastoncillos de algodón",
    "d": "Envase redondo grande · Cantidad no legible",
    "c": "Aseo",
    "p": 700,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165123_1.jpg",
    "id": 2016,
    "img": "/products/real/bastoncillos-grandes.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165123_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "palillos",
    "n": "Palillos de madera",
    "d": "Envase con tapa decorada · Colores surtidos",
    "c": "Aseo",
    "p": 700,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165123_1.jpg",
    "id": 2017,
    "img": "/products/real/palillos.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165123_1.jpg",
    "stock": null
  },
  {
    "sharedProductId": "truearth-spring",
    "n": "Detergente en tiras Net Zero Co by Tru Earth",
    "d": "Spring Breeze · 20 tiras",
    "c": "Aseo",
    "p": 4500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165128.jpg",
    "id": 2018,
    "img": "/products/real/truearth-spring.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165128.jpg",
    "stock": null
  },
  {
    "sharedProductId": "belle-france-antitransfert",
    "n": "Toallitas antitransferencia Belle France",
    "d": "Caja de 25 unidades",
    "c": "Aseo",
    "p": 3000,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165128.jpg",
    "id": 2019,
    "img": "/products/real/belle-france-antitransfert.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165128.jpg",
    "stock": null
  },
  {
    "sharedProductId": "harmony-lemon",
    "n": "Jabón Harmony Lemon",
    "d": "Fruit series · Una pastilla en envoltorio",
    "c": "Aseo",
    "p": 450,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165138.jpg",
    "id": 2020,
    "img": "/products/real/harmony-lemon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165138.jpg",
    "stock": null
  },
  {
    "sharedProductId": "parex-s",
    "n": "Bolsas de basura Parex S",
    "d": "20 L · 40 × 50 cm · 20 bolsas",
    "c": "Aseo",
    "p": 1750,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165144.jpg",
    "id": 2021,
    "img": "/products/real/parex-s.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165144.jpg",
    "stock": null
  },
  {
    "sharedProductId": "parex-m",
    "n": "Bolsas de basura Parex M",
    "d": "35 L · 55 × 60 cm · 30 bolsas",
    "c": "Aseo",
    "p": 2500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165144.jpg",
    "id": 2022,
    "img": "/products/real/parex-m.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165144.jpg",
    "stock": null
  },
  {
    "sharedProductId": "happy-baby-soap",
    "n": "Jabón Happy Baby",
    "d": "Cream soap · Manzanilla y sumac · Caja",
    "c": "Aseo",
    "p": 2500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165150.jpg",
    "id": 2023,
    "img": "/products/real/happy-baby-soap.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165150.jpg",
    "stock": null
  },
  {
    "sharedProductId": "amber-sugar-cookie",
    "n": "Desodorante Amber Sugar Cookie",
    "d": "60 g · Envase rosa",
    "c": "Aseo",
    "p": 3500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165157.jpg",
    "id": 2024,
    "img": "/products/real/amber-sugar-cookie.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165157.jpg",
    "stock": null
  },
  {
    "sharedProductId": "rose-honey",
    "n": "Toallitas húmedas Rose Honey y Camomile",
    "d": "Paquete con tapa rígida · Cantidad no legible",
    "c": "Aseo",
    "p": 1100,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165200.jpg",
    "id": 2025,
    "img": "/products/real/rose-honey.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165200.jpg",
    "stock": null
  },
  {
    "sharedProductId": "ronza-lemon",
    "n": "Toallitas húmedas Ronza Lemon",
    "d": "Paquete de 15 unidades",
    "c": "Aseo",
    "p": 500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165200.jpg",
    "id": 2026,
    "img": "/products/real/ronza-lemon.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165200.jpg",
    "stock": null
  },
  {
    "sharedProductId": "astera-kids",
    "n": "Pasta dental Astera Kids",
    "d": "Ice cream · Caja",
    "c": "Aseo",
    "p": 1500,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165203.jpg",
    "id": 2027,
    "img": "/products/real/astera-kids.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165203.jpg",
    "stock": null
  },
  {
    "sharedProductId": "colgate-advanced",
    "n": "Pasta dental Colgate Advanced White",
    "d": "100 mL · 140 g",
    "c": "Aseo",
    "p": 1300,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165207.jpg",
    "id": 2028,
    "img": "/products/real/colgate-advanced.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165207.jpg",
    "stock": null
  },
  {
    "sharedProductId": "colgate-triple",
    "n": "Pasta dental Colgate Triple Action",
    "d": "100 mL",
    "c": "Aseo",
    "p": 1200,
    "currency": "CUP",
    "sourcePhoto": "IMG_20261009_165207.jpg",
    "id": 2029,
    "img": "/products/real/colgate-triple.webp",
    "provisional": false,
    "source": "store-photo",
    "sourceImage": "/catalog-sources/IMG_20261009_165207.jpg",
    "stock": null
  }
];
