"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useAdminAuth} from "../../../lib/useAdminAuth";
import {products} from "../../../lib/catalog";
import {supabase} from "../../../lib/supabase";
import {mergeCatalog} from "../../../lib/catalog-overrides.mjs";
import {money} from "../../../lib/commerce.mjs";
export default function ProductAdmin(){
 const {loading,user}=useAdminAuth();
 const [rows,setRows]=useState(products),[q,setQ]=useState(""),[filter,setFilter]=useState("Todos"),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const {data,error}=await supabase.from("colo_product_overrides").select("*");if(error){setMessage("No se pudo cargar el catálogo actualizado.");return}const index=new Map((data||[]).map(x=>[Number(x.product_id),x]));setRows(products.map(p=>{const o=index.get(p.id);return o?{...mergeCatalog([p],[{...o,active:true}])[0],active:o.active}:p}))}
 useEffect(()=>{if(user)load()},[user]);
 const list=rows.filter(p=>[p.n,p.d,p.c,p.sharedProductId].join(" ").toLowerCase().includes(q.toLowerCase())&&(filter==="Todos"||filter==="Precio por confirmar"&&p.p==null||filter==="Agotados"&&p.stock===0||filter==="Ocultos"&&p.active===false));
 function open(p){setMessage("");setEdit({...p,p:p.p??"",d:p.d||"",active:p.active!==false})}
 async function save(e){e.preventDefault();setBusy(true);setMessage("");const price=edit.p===""?null:Number(edit.p),stock=Number(edit.stock);if(!edit.n.trim()||!edit.c.trim()||!Number.isInteger(stock)||stock<0||price!==null&&(!Number.isFinite(price)||price<=0)||!/^\/(?!\/)|^https:\/\//.test(edit.img)){setMessage("Revisa nombre, categoría, precio, existencias y la ruta de imagen.");setBusy(false);return}const {error}=await supabase.from("colo_product_overrides").upsert({product_id:edit.id,name:edit.n.trim(),description:edit.d,category:edit.c,price,stock,image:edit.img,active:edit.active,updated_at:new Date().toISOString()});setBusy(false);if(error){setMessage("No se guardó el cambio. Reintenta.");return}setEdit(null);await load();setMessage("Cambios guardados y disponibles en la tienda.")}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setMessage("Selecciona JPG, PNG o WebP de hasta 5 MB.");return}setBusy(true);setMessage("");const ext=file.type==="image/jpeg"?"jpg":file.type==="image/png"?"png":"webp",path=edit.id+"/"+crypto.randomUUID()+"."+ext;const {error}=await supabase.storage.from("colo-catalog").upload(path,file,{contentType:file.type,upsert:false});setBusy(false);if(error){setMessage("No se pudo subir la imagen. Reintenta.");return}const {data}=supabase.storage.from("colo-catalog").getPublicUrl(path);setEdit(p=>({...p,img:data.publicUrl}));setMessage("Imagen cargada. Guarda los cambios para publicarla.")}
 function exportCsv(){const cells=v=>'"'+String(v??"").replaceAll('"','""')+'"';const data=[["ID","Producto","Categoría","Precio CUP","Stock","Imagen","Estado"],...list.map(p=>[p.sharedProductId,p.n,p.c,p.p,p.stock,p.img,p.p==null?"Precio por confirmar":"Confirmado"])].map(r=>r.map(cells).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='colo-productos.csv';a.click();URL.revokeObjectURL(url)}
 if(loading||!user)return <main className="adminShell">Cargando panel…</main>;
 return <main className="adminShell"><Link href="/admin">← Pedidos</Link><h1>Productos</h1><p>{rows.length} productos · {rows.filter(p=>p.p==null).length} precios por confirmar</p><div className="adminTools"><input aria-label="Buscar producto" placeholder="Producto, marca o categoría" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Filtrar productos" value={filter} onChange={e=>setFilter(e.target.value)}>{["Todos","Precio por confirmar","Agotados","Ocultos"].map(x=><option key={x}>{x}</option>)}</select><button onClick={exportCsv}>Exportar CSV</button></div>{message&&<p role="status">{message}</p>}<div style={{overflowX:"auto"}}><table className="productAdmin"><thead><tr><th>Imagen</th><th>Producto</th><th>Precio</th><th>Stock</th><th></th></tr></thead><tbody>{list.map(p=><tr key={p.id}><td><img src={p.img} alt={p.n} width="80" height="80"/></td><td><b>{p.n}</b><small>{p.d}</small><small>{p.c}{p.active===false?" · Oculto":""}</small></td><td>{money(p.p)}</td><td>{p.stock}</td><td><button onClick={()=>open(p)}>Editar</button></td></tr>)}</tbody></table></div>{edit&&<div className="adminEditBackdrop"><form className="adminEditForm" onSubmit={save}><h2>Editar producto</h2><img src={edit.img} alt={edit.n}/><label>Nombre<input required value={edit.n} onChange={e=>setEdit({...edit,n:e.target.value})}/></label><label>Presentación<input value={edit.d} onChange={e=>setEdit({...edit,d:e.target.value})}/></label><label>Categoría<input required value={edit.c} onChange={e=>setEdit({...edit,c:e.target.value})}/></label><label>Precio CUP<input type="number" min="0.01" step="0.01" placeholder="Vacío: por confirmar" value={edit.p} onChange={e=>setEdit({...edit,p:e.target.value})}/></label><label>Unidades disponibles<input required type="number" min="0" step="1" value={edit.stock} onChange={e=>setEdit({...edit,stock:e.target.value})}/></label><label>Subir imagen<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={upload}/></label><label>Ruta o enlace HTTPS de imagen<input required value={edit.img} onChange={e=>setEdit({...edit,img:e.target.value})}/></label><label><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Visible en tienda</label>{message&&<p role="alert">{message}</p>}<div><button type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancelar</button><button disabled={busy}>{busy?"Guardando…":"Guardar cambios"}</button></div></form></div>}</main>
}
