"use client";
import Link from "next/link";
import {useState} from "react";
import {useAdminAuth} from "../../../lib/useAdminAuth";
import {products} from "../../../lib/catalog";
import review from "../../../lib/catalog-review.json";
const rows=[...products.map(p=>({...p,status:"Publicado"})),...review.map(p=>({...p,status:"Pendiente"}))];
function csvCell(value){let s=String(value??"");if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
export default function ProductAdmin(){const {loading,user}=useAdminAuth();const [q,setQ]=useState(""),[status,setStatus]=useState("Todos");const list=rows.filter(p=>(status==="Todos"||p.status===status)&&[p.n,p.sharedProductId,p.sourcePhoto,p.c].join(" ").toLowerCase().includes(q.toLowerCase()));
function download(){const data=[["Producto","ID compartido","Categoría","Precio CUP","Estado","Foto original","Revisión"],...list.map(p=>[p.n,p.sharedProductId,p.c,p.p,p.status,p.sourcePhoto,p.reason])].map(row=>row.map(csvCell).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob(["\uFEFF"+data],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="productos-CUP.csv";a.click();URL.revokeObjectURL(url)}
if(loading||!user)return <main className="adminShell">Cargando panel…</main>;
return <main className="adminShell"><Link href="/admin">← Pedidos</Link><h1>Productos</h1><p>{products.length} publicados · {review.length} pendientes · Moneda CUP</p><p>Catálogo con precios de las fotos confirmados por el propietario. Los pendientes no aparecen en la tienda. Las modificaciones se guardan en el catálogo del repositorio.</p><div className="adminTools"><input aria-label="Buscar producto" placeholder="Producto, ID o foto" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Estado" value={status} onChange={e=>setStatus(e.target.value)}>{["Todos","Publicado","Pendiente"].map(s=><option key={s}>{s}</option>)}</select><button onClick={download}>Exportar CSV</button></div><div style={{overflowX:"auto"}}><table className="productAdmin"><thead><tr><th>Imagen</th><th>Producto</th><th>Precio CUP</th><th>Estado</th><th>Origen / revisión</th></tr></thead><tbody>{list.map(p=><tr key={p.sharedProductId}><td>{p.img?<img src={p.img} alt={p.n} width="80" height="80"/>:"Por crear"}</td><td><b>{p.n}</b><small>{p.d||p.c}</small><small>{p.sharedProductId}</small></td><td>{p.p?.toLocaleString("es-CU")??"Por confirmar"}</td><td>{p.status}</td><td><a href={p.sourceImage} target="_blank" rel="noreferrer">{p.sourcePhoto}</a><small>{p.reason}</small></td></tr>)}</tbody></table>{!list.length&&<p>No hay resultados.</p>}</div></main>}
