import csv,json,html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
s=(root/'lib/catalog.js').read_text();products=json.loads(s[s.index('['):s.rindex(']')+1])
out=root/'docs/handoff';out.mkdir(parents=True,exist_ok=True)
fields=['sharedProductId','n','d','c','p','stock','priceStatus','imageKind','provisional','img','sourceImage','reason']
for filename,rows in [('catalogo-completo.csv',products),('precios-por-confirmar.csv',[p for p in products if p['p'] is None]),('imagenes-provisionales.csv',[p for p in products if p.get('provisional')]),('imagenes-pendientes.csv',[p for p in products if p.get('imageKind')=='store-photo'])]:
 with (out/filename).open('w',encoding='utf-8-sig',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
base='https://frutos-secos-drab.vercel.app'
cards=[]
for p in products:
 pending=p['p'] is None;generated=p.get('imageKind')=='generated'
 cards.append('<article data-pending="'+str(pending).lower()+'" data-generated="'+str(generated).lower()+'" data-imagepending="'+str(p.get('imageKind')=='store-photo').lower()+'"><img loading="lazy" src="'+html.escape(base+p['img'])+'" alt="'+html.escape(p['n'])+'"><h2>'+html.escape(p['n'])+'</h2><p>'+html.escape(p.get('d') or '')+'</p><b>'+('Precio por confirmar' if pending else f"{p['p']:,.0f} CUP")+'</b><small>'+html.escape(p.get('reason') or '')+'</small><span>'+('Imagen provisional' if generated else 'Imagen existente' if p.get('imageKind')!='store-photo' else 'Foto de tienda pendiente de sustituir')+'</span><a target="_blank" rel="noreferrer" href="'+html.escape(base+p['sourceImage'])+'">Ver foto original y etiqueta</a></article>')
text='<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revisión del catálogo de Colo</title><style>body{font-family:Helvetica,Arial,sans-serif;background:#f8f7f4;color:#1f2d44;margin:0;padding:24px}header{max-width:1100px;margin:auto}h1{font-size:32px}nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button{padding:12px 18px;background:white;border:1px solid #ddd;border-radius:30px;cursor:pointer}.grid{max-width:1100px;margin:auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px}article{background:white;border-radius:20px;padding:16px;display:grid;gap:8px}article[hidden]{display:none}img{width:100%;height:210px;object-fit:contain}h2{font-size:16px;margin:0}p{margin:0;font-size:14px}small{color:#6b7280}span{font-size:12px;color:#a23d46}a{font-size:13px;color:#1f2d44}</style><header><h1>Revisión del catálogo</h1><p>'+str(len(products))+' productos · '+str(sum(p['p'] is None for p in products))+' precios por confirmar · '+str(sum(p.get('imageKind')=='generated' for p in products))+' imágenes provisionales publicadas · 216 fotos individuales pendientes</p><p>La revisión y sustitución de fotos individuales sigue en curso. Las fotos pendientes conservan su fuente original hasta poder sustituirse. Las imágenes provisionales se pueden cambiar desde el panel. Los precios pendientes se consultan por WhatsApp. Una observación Southern Dry Roasted queda pendiente de determinar si es variante o duplicado.</p><nav><button data-filter="all">Todos</button><button data-filter="pending">Precio por confirmar</button><button data-filter="generated">Imágenes provisionales</button><button data-filter="imagepending">Fotos pendientes</button></nav></header><main class="grid">'+''.join(cards)+'</main><script>document.querySelectorAll("button[data-filter]").forEach(b=>b.addEventListener("click",()=>{const type=b.dataset.filter;document.querySelectorAll("article").forEach(a=>a.hidden=type!=="all"&&a.dataset[type]!=="true")}))</script></html>'
(out/'revision-catalogo.html').write_text(text)
(root/'public/revision-catalogo.html').write_text(text)
print(json.dumps({'products':len(products),'pendingPrices':sum(p['p'] is None for p in products),'generatedImages':sum(p.get('imageKind')=='generated' for p in products)}))
